definitions:
  - name: "UEAssociatedLogicalE1ConnectionItemRes"
    type: "SEQUENCE"
    from_ie_set: "UE-associatedLogicalE1-ConnectionItemRes"

  - name: "UEAssociatedLogicalE1ConnectionListRes"
    type: "LIST"
    of_type: "UEAssociatedLogicalE1ConnectionItemRes"
    max_val: "maxnoofIndividualE1ConnectionsToReset"

  - name: "UEAssociatedLogicalE1ConnectionItemResAck"
    type: "SEQUENCE"
    from_ie_set: "UE-associatedLogicalE1-ConnectionItemResAck"

  - name: "UEAssociatedLogicalE1ConnectionListResAck"
    type: "LIST"
    of_type: "UEAssociatedLogicalE1ConnectionItemResAck"
    max_val: "maxnoofIndividualE1ConnectionsToReset"

  # This patch creates a SEQUENCE with explicitly defined members.
  - name: "CriticalityDiagnostics-IE-Item"
    type: "SEQUENCE"
    members:
      - { ie: "iECriticality", type: "Criticality", presence: "mandatory" }
      - { ie: "iE-ID", type: "ProtocolIE-ID", presence: "mandatory" }
      - { ie: "typeOfError", type: "TypeOfError", presence: "mandatory" }

  - name: "CriticalityDiagnostics-IE-List"
    type: "LIST"
    of_type: "CriticalityDiagnostics-IE-Item"

  - name: "GTPTLA-Item"
    type: "SEQUENCE"
    members:
      - { ie: "gTPTransportLayerAddresses", type: "TransportLayerAddress", presence: "mandatory" }
      - { ie: "iE-Extensions", type: "ProtocolExtensionContainer", presence: "optional" }

  - name: "GTPTLAs"
    type: "LIST"
    of_type: "GTPTLA-Item"
    max_val: "maxnoofGTPTLAs"

  - name: "DLUPTNLAddressToUpdateList"
    type: "LIST"
    of_type: "DLUPTNLAddressToUpdateItem"
    max_val: "maxnoofTNLAddresses"

  - name: "UL-UP-TNL-Address-To-Update-List"
    type: "LIST"
    of_type: "UL-UP-TNL-Address-To-Update-Item"
    max_val: "maxnoofTNLAddresses"

  - name: "GNB-CU-UP-TNLA-To-Remove-List"
    type: "LIST"
    of_type: "GNB-CU-UP-TNLA-To-Remove-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "GNB-CU-CP-TNLA-To-Add-List"
    type: "LIST"
    of_type: "GNB-CU-CP-TNLA-To-Add-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "GNB-CU-CP-TNLA-To-Update-List"
    type: "LIST"
    of_type: "GNB-CU-CP-TNLA-To-Update-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "GNB-CU-CP-TNLA-To-Remove-List"
    type: "LIST"
    of_type: "GNB-CU-CP-TNLA-To-Remove-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "GNB-CU-CP-TNLA-Setup-List"
    type: "LIST"
    of_type: "GNB-CU-CP-TNLA-Setup-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "GNB-CU-CP-TNLA-Failed-To-Setup-List"
    type: "LIST"
    of_type: "GNB-CU-CP-TNLA-Failed-To-Setup-Item"
    max_val: "maxnoofTNLAssociations"

  - name: "PrivateIE-ID"
    type: "CHOICE"
    members:
      - { ie: "local", type: "INTEGER", presence: "mandatory" }
      - { ie: "global", type: "OBJECT IDENTIFIER", presence: "mandatory" }


  - name: "PrivateIEField"
    type: "SEQUENCE"
    members:
      - { ie: "id", type: "PrivateIE-ID", presence: "mandatory" }
      - { ie: "criticality", type: "Criticality", presence: "mandatory" }
      - { ie: "value", type: "ANY", presence: "mandatory" }

  - name: "ULUPTNLAddressToUpdateList"
    type: "LIST"
    of_type: "ULUPTNLAddressToUpdateItem"
    max_val: "maxnoofTNLAddresses"

  - name: "ProtocolIE-Field"
    type: "SEQUENCE"
    members:
      - { ie: "id", type: "ProtocolIE-ID", presence: "mandatory" }
      - { ie: "criticality", type: "Criticality", presence: "mandatory" }
      - { ie: "value", type: "ANY", presence: "mandatory" }


  - name: "PrivateIE-Field"
    type: "SEQUENCE"
    members:
      - { ie: "id", type: "PrivateIE-ID", presence: "mandatory" }
      - { ie: "criticality", type: "Criticality", presence: "mandatory" }
      - { ie: "value", type: "ANY", presence: "mandatory" }

  - name: "ProtocolIE-Container"
    type: "LIST"
    of_type: "ProtocolIE-Field"
    max_val: "maxProtocolIEs"

  - name: "PrivateIE-Container"
    type: "LIST"
    of_type: "PrivateIE-Field"
    max_val: "maxPrivateIEs"

  # 3. Define the remaining special-case abstract types.

  # ProtocolIE-SingleContainer is a simple wrapper around one IE-Field.
  - name: "ProtocolIE-SingleContainer"
    type: "SEQUENCE"
    members:
      - { ie: "value", type: "ProtocolIE-Field", presence: "mandatory" }

  # PrivateMessage-IEs is just another name for PrivateIEContainer.
  - name: "PrivateMessage-IEs"
    type: "ALIAS"
    alias_of: "PrivateIEContainer"

  # ProtocolIE-ContainerList is a meta-template we don't need to generate directly.
  # We provide a placeholder to prevent "undefined" errors if it's ever referenced.
  - name: "ProtocolIE-ContainerList"
    type: "SEQUENCE"
    members: [] # Empty sequence